### ISSUE TITLE
Write a quickstart guide for central documentation site

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/zos-cli#127]

**Comment by elopio** [comment]
I took info from the README of zos-cli and from development.md to write the Getting started that will go on the overview of the docs site, and a more comprehensive guide called "Building [...]". This is WIP in https://github.com/zeppelinos/zos-docs/pull/12
Any feedback is appreciated.

**Comment by fiiiu** [comment]
Closed in https://github.com/zeppelinos/zos-docs/pull/24.
