### ISSUE TITLE
Global artifacts need to be set if calling scripts from js

### ISSUE THREAD

**Issue by nventuro** [zeppelinos/zos-cli#139]
To deploy from a JS script using the cli commands, the scripts themselves should be imported (and the whole script executed under `trufle exec`), but using them fails unless `global.artifacts` has been set beforehand.

```
global.artifacts = artifacts;
const zosPush = require('zos/lib/scripts/push').default;
const zosCreate = require('zos/lib/scripts/create-proxy').default;
```

**Comment by facuspagnuolo** [comment]
This a Truffle `exec` issue we already reported, you can avoid that issue by using the `runWithTruffle` function of zOS. However, we are already thinking of removing Truffle artifacts
