### ISSUE TITLE
Commands that don't immediately interact with a network should not require a network parameter

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos-cli#14]
i.e. `zos init MyProject 0.0.1` does not work atm while `zos init MyProject 0.0.1 --network local` does.

However, the command only writes to a json file, so it doesn't really need to know about the network.
Since this requirement probably exists because everything goes through truffle exec, consider using a default network with the truffle wrapper.

**Comment by spalladino** [comment]
See #32

**Comment by spalladino** [comment]
Fixed
