### ISSUE TITLE
Command file names should be the same as the commands they hold

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos-cli#140]
i.e. the `create` command is defined in `create-proxy.js` file, which should be renamed to `create.js`.

Same for `add`, `upgrade`, etc

**Comment by spalladino** [comment]
-1. The name of the commands exposed make sense in the context of a command line, while the file names are more descriptive. I'd leave them as is.

**Comment by facuspagnuolo** [comment]
Agree with @spalladino, closing
