### ISSUE TITLE
Check if newly created proxies have an initialize method

### ISSUE THREAD

**Issue by nventuro** [zeppelinos/zos-cli#145]
As of the MVP, `zos create Contract` succeeds with no warnings for a contract that has an initialize method. We should consider either:

a) Issuing a warning message about the created proxy not having been yet initialized
b) Force initialize to be called via `zos create` (which would limit other ways of using zos, e.g. by calling cli-like functions from JavaScript)

This would most likely require inspecting the contract artifact. Maybe we could also check if the method has the `isInitializer` modifier?

**Comment by spalladino** [comment]
Also, check if they have a constructor, and if they do, raise a warning.
