### ISSUE TITLE
Add new `deploy` (push + upgrade) command in CLI

### ISSUE THREAD

**Issue by martriay** [zeppelinos/zos-cli#151]
I think a "full push" functionality could be useful, automatizing `push` and `upgrade` for the updated implementations. This can be implemented either as a command or a flag.
I propose `zos deploy` or `zos push --upgrade` for each case.

**Comment by facuspagnuolo** [comment]
Closing this since it's duplicated in https://github.com/zeppelinos/zos-cli/issues/123
