### ISSUE TITLE
Store contract versions in network file

### ISSUE THREAD

**Issue by martriay** [zeppelinos/zos-cli#152]
I think that adding the contract version to each contract in the `contracts` key of zos' network file would be of much help to both the user and the CLI. It could be used to print a richer `zos status` or to check differences while upgrading, by comparing it against current proxy versions.

It would look like this:

```js
  "contracts": {
    "Employment": {
      "address": "0x7f132ebccf22c2faab02a40e2169129360df1c1c",
      "version": "0.1.0",                        <------------ HERE
      "bytecodeHash": "fba9e1e689e2b7f58817dfc53b40bd17a5769b65fa52a37e98d4292f258a1213"
    }
  }
```

**Comment by spalladino** [comment]
@martriay reviewing this issue, there seems to be no way for a specific `contract` version to differ from the global `version` set at the root of the `package.network.zos.json` file. Can you think of any, or should I close the issue?

**Comment by spalladino** [comment]
Discussed offline. Closing.
