### ISSUE TITLE
Handle undefined command

### ISSUE THREAD

**Issue by martriay** [zeppelinos/zos-cli#155]
Nowadays you can execute any command without any error or feedback message.  This includes but it's not limited to:

```
zos asd
zos pickle
zos pepsi
zos zos
zos buidl
zos soz
```

Consider throwing to ensure proper process behavior for automation.

**Comment by spalladino** [comment]
Note that commander already provides a way to handle this:
```js
// error on unknown commands
program.on('command:*', function () {
  console.error('Invalid command: %s\nSee --help for a list of available commands.', program.args.join(' '));
  process.exit(1);
});
```
