### ISSUE TITLE
Running link command removes all npm links

### ISSUE THREAD

**Issue by eternauta1337** [zeppelinos/zos-cli#178]
Since the command runs an npm install, all `npm link <pkg>` are lost.

This could be quite annoying.

**Comment by facuspagnuolo** [comment]
As @spalladino mentioned, you can run `zos link X --no-install` in case you have linked that dependency locally. However, we may want to consider adding a validation to check if you already have a linked dependency before installing it. And in that case, we may need a `--force-install` option as a consequence.
