### ISSUE TITLE
Consider writing the proxy deployment address in the build json file

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-cli#206]
When deploying a contract instance, Truffle writes a `deployedAddress` (disclaimer: actual field name may be different) field in the JSON file of a contract in the build folder. This enables retrieving an instance via `MyContract.deployed()`. 

Evaluate writing such field upon create-proxy, to allow users to work with the `deployed()` method. Check how truffle handles deployment on different networks here.

**Comment by makoto** [comment]
This feature is probably important to support framework like https://github.com/trufflesuite/drizzle where it wraps web3 object under redux store so I cannot instantiate contract with ZOS proxy id.

**Comment by roschler** [comment]
Yes, desperately need this!  I'm currently trying crazy stuff like this in an attempt to be able debug Proxy contracts from a Truffle console session because I can't use the `deployed()` interface:

https://github.com/trufflesuite/truffle/issues/988

**Comment by roschler** [comment]
@spalladino Is there anything I can do myself in the meantime to fill in that deployed address, using the addresses in the `zos.<network>.json` file, something I can edit manually?  I don't care if I have to do it every time I deploy.

**Comment by roschler** [comment]
@facuspagnuolo Thanks.
