### ISSUE TITLE
Review creation of .gitkeep files with `init` command

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/zos-cli#224]
Running `zos init` left my tree like this: 
```
contracts/
└──  .gitkeep
migrations/
└── .gitkeep
...
```
both .gitkeep files contain:
```
null
```

This is confusing and (I think) not necessary.

**Comment by nventuro** [comment]
Which part do you find confusing? `.gitkeep` files are standard practice to get around the fact that git doesn't track directories (so an empty directory will not be commited). They are usually empty though (i.e. created with `touch dir/.gitkeep`).

And afaik truffle will only look for contracts in that directory, so it makes sense to create it for the user.

**Comment by maraoz** [comment]
why should `zos` deal with `git` specifics? It's weird IMO

**Comment by facuspagnuolo** [comment]
`.gitkeep` files should be empty
