### ISSUE TITLE
Running zos push without the --deploy-stdlib in an app with stdlib breaks

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/zos-cli#227]
If the app uses a stdlib (`zos.json` contains `stdlib` configuration), and we `push` without the `--deploy-stdlib` flag, `zos` breaks with a confusing error: 
```
$ zos push -n local
...
ENOENT: no such file or directory, open 'node_modules/openzeppelin-zos/zos.local.json'
```

This is probably due to `zos` looking for the 'local' config for stdlib, we should output a better error.

**Comment by facuspagnuolo** [comment]
Let's improve the error message

**Comment by luyzdeleon** [comment]
If I might weigh in on this one, it would be cool to add this on the quick start guide as well: https://docs.zeppelinos.org/docs/building.html
