### ISSUE TITLE
Make installation much faster

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-cli#234]
Installing `zos` via npm can take as much as 75 seconds and probably a lot more in slower connections.

This is mostly due the amount of dependencies, which at the moment are around 1060.

**Comment by facuspagnuolo** [comment]
Having https://github.com/zeppelinos/zos-lib/issues/94 done, will make it faster

**Comment by frangio** [comment]
@facuspagnuolo Why is that? The files included in the package should be already compiled.

Don't get me wrong though, I'm all for removing Babel. :stuck_out_tongue:

**Comment by facuspagnuolo** [comment]
@frangio I'm trying to see why babel is being declared as non-dev dependency :/

**Comment by facuspagnuolo** [comment]
We are still waiting for the Truffle team to release a new version including the latest release of `ganache-cli` where webpack is removed from the production dependencies list.
