### ISSUE TITLE
Zos client needs to be installed globally and with Node.js 8.11.1

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-cli#236]
The Basil tutorial simply tells the user to install zos locally using the npm.  That didn't work for me.  Whenever I ran the zos commandthe shell told me that command could not be found.  I had to install zos globally using npm, and that only worked with Node.JS version 8.11.1.  With 6.7.0 I got an assert failure whenever I tried to run zos.  More details here:

https://github.com/zeppelinos/basil/issues/30

**Comment by roschler** [comment]
Prefixing `npx` to any `zos` commands appears to solve that problem (thanks Vamses).

**Comment by facuspagnuolo** [comment]
Closing this issue in favour of zeppelinos/basil#30
