### ISSUE TITLE
Store transaction IDs in zos files

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos-cli#239]
We should write transaction IDs into the network zos file. This could be used to recover from any network or connection issues.

**Comment by frangio** [comment]
cc @ajsantander had some ideas for this.

**Comment by facuspagnuolo** [comment]
Related to https://github.com/zeppelinos/zos-lib/issues/149

**Comment by spalladino** [comment]
Closing in favour of #319
