### ISSUE TITLE
Contracts deployed with ZOS are not seen by Truffle console

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-cli#242]
I've been struggling with this one for a while now, especially since I've been debugging an **owner** revert failure in Ownable while working on the Basil tutorial.  Usually when you migrate contracts to Ganache with Truffle, the Truffle console is "aware" of them.  You can use the Truffle console  _networks_ command and it will show you the list of deployed contracts.  However, there's something about the way ZOS deploys contracts that nullifies that.  When you do the _networks_ command you get back the status message "no contracts deployed".

Because of this you can't use the "<contract name>.deployed()" Promise based function, which makes working with the contracts and subsequently debugging problems much harder; because you can't  take advantage of the "instance" object that Promise returns to you in your callback function.  That instance object has the `Web3.js` interface, which makes interacting with the contract instance much more convenient.  Instead, with ZOS deployed contracts,  you have to use the "<contract name>.at(address)" method and that method only seems to surface the methods/properties declared in the contract ABI.

Why can't I work with the contracts like I usually can in the Truffle console and is there any way to recover the interface provided by the ".deployed()" technique?

**Comment by facuspagnuolo** [comment]
Thanks @roschler! We are already considering to write the deployed address of the upgradeable 
 smart contracts in the build json file to solve this issue. Please see https://github.com/zeppelinos/zos-cli/issues/206

**Comment by roschler** [comment]
@facuspagnuolo Sure.  Just commented on #206
