### ISSUE TITLE
What address from zos.<network>.json should be used with ZOS commands?

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-cli#244]
I'm following along the Basil tutorial, trying desperately to debug an `owner` revert failure when I reach the step when `setToken()` is called on the proxied _BasilERC721_ contract.  The tutorial isn't clear on which address should be exported to the `BASIL_ADDRESS` environment variable: it simply states that after the `npx zos push --from $OWNER --network local` command it "prints out the address of the deployed basil contract".  Unfortunately it prints out several other addresses at the same time.

To make things clearer, which address from the `zos.<network>.json` file should be passed to the commands that require the contract address?  For example, like the commands that begin with `BasilERC721.at(<contract address>)`.  Is it the `contracts.Basil.address`, `proxies.Basil.address`, 
 `proxies.Basil.implementation`, or `app` address?  I would guess it's the `app` address because otherwise there's a risk of circumventing the proxy and going right to the logic contract, defeating the proxy.  But I want to make sure:

```json
{
  "contracts": {
    "Basil": {
      "address": "0x6ed79aa1c71fd7bdbc515efda3bd4e26394435cc",
      "bytecodeHash": "93e5232cedc10f89615de9b638a9a025dbd87a0e76127ee16695255bea4caf85"
    }
  },
  "proxies": {
    "Basil": [
      {
        "address": "0x4849038be95fe6e42da67c9edbe411709e9c6780",
        "version": "0.0.2",
        "implementation": "0x6ed79aa1c71fd7bdbc515efda3bd4e26394435cc"
      }
    ],
    "MintableERC721Token": [
      {
        "address": "0x5c4f7148f0bbc0328cb487f72b2ba71a30895a36",
        "version": "0.0.2",
        "implementation": "0xad888d0ade988ebee74b8d4f39bf29a8d0fe8a8d"
      }
    ]
  },
  "app": {
    "address": "0x67b5656d60a809915323bf2c40a8bef15a152e3e"
  },
  "version": "0.0.2",
  "package": {
    "address": "0x59d3631c86bbe35ef041872d502f218a39fba150"
  },
  "provider": {
    "address": "0x0e696947a06550def604e82c26fd9e493e576337"
  },
  "stdlib": {
    "address": "0x21a59654176f2689d12e828b77a783072cd26680",
    "customDeploy": true,
    "name": "openzeppelin-zos",
    "version": "1.9.1"
  }
```

Bonus question: is it _really_ possible to debug ZOS proxied contracts now with the Truffle console debug command?  I'm getting all kinds of errors including "null context" errors and other oddities.  I'm wondering if the Truffle console debug command really only works with migrations done directly by Truffle.  I've spent over 5 full days working on my `onlyOwner` revert problem and I'm beginning to suspect its possibly a problem with the proxy contract being the owner of the proxied/logic-contract and not my Ganache accounts[0] address.  If not that, than perhaps the state variables managed by the proxy contract `Assembly{}` code is getting twisted up.  I'm currently conversing with _g. nicholas d'andrea_ from Truffle on Gitter, and I'm getting the feeling I'm banging my head against the wall in a futile manner.

**Comment by facuspagnuolo** [comment]
Hi @roschler, you should always use the proxy address, then the proxy will handle the delegation to the logic contract (implementation) for you. Thus, for the `Basil` contract, you should use the `proxies.Basil.address` of the `zos.<network>.json` file.

Regarding debugging with Truffle, we haven't tested that yet, although it is in our plans. Please if you find any issues with the Basil tutorial, feel free to open new tickets in [its repository](https://github.com/zeppelinos/basil/issues). 

Thanks!

**Comment by roschler** [comment]
@facuspagnuolo Hi.  I have a few issues active in the Basil repository and Basil tutorial docs already, thanks.

Regarding "...you should always use the proxy address, then the proxy will handle the delegation to the logic contract (implementation) for you."

Are you sure?  The Basil tutorial tells you to use the address "printed" out by the `zos push` command and that address is the `app` address and _not_ the proxy address for the Basil contract itself.  Given my example `zos.local.json` above, and obviously with the understanding the addresses shown are just for reference and would be different every time you run the tutorial:

```0x67b5656d60a809915323bf2c40a8bef15a152e3e - is the "app" address and is what the tutorial tells you to use 
0x4849038be95fe6e42da67c9edbe411709e9c6780 - is the proxy address for the Basil contract ("proxies.Basil.address")

This makes more sense to me if I'm not completely wrong about this.  If you used the `proxies.Basil.address` value, which is **only** for the proxied Basil contract, you would have to do address juggling for _every_ proxied contract when you add other contracts in the future.

If you use the `app` address as I believe the Basil tutorial tells you to do, you go through the ZOS app directory and this will look up the correct proxy address for you based on the contract you are trying to call.  Therefore you don't have to worry about the proxy address for each proxied contract, as indicated by the code in `AppDirectory.sol`:

```js
 /**
  * @dev Returns the implementation address for a given contract name.
  * If the implementation is not found in the directory, it will search in the
  * standard library.
  * @param contractName Name of the contract.
  * @return Address where the contract is implemented, or 0 if it is not
  * found.
  */
 function getImplementation(string contractName) public view returns (address) {
   address implementation = super.getImplementation(contractName);
   if(implementation != address(0)) return implementation;
   if(stdlib != address(0)) return stdlib.getImplementation(contractName);
   return address(0);
 }
```
Do I have this all wrong?

**Comment by roschler** [comment]
regarding "debugging".

Without the ".deployed()" address being filled in by ZOS as per this issue:

https://github.com/zeppelinos/zos-cli/issues/206

There's no way to effectively debug because you can't get the ABI into Truffle console.  I tried to do it with an external script using that feature of Truffle console, as per the recommendation of one of Truffle's engineers:

https://github.com/trufflesuite/truffle/issues/988

But sadly any variables you create do **not** persist into the Truffle console Javascript VM, so the ABI I read for the ZOS proxy contract could not be passed on to the Truffle console.  Without the ABI I can't use Proxy.at("<address>") and as I mentioned above currently ZOS is not setting the ".deployed()" address, so there's no reasonable way to make method calls against a deployed instance of a proxied contract from within Truffle console.  If you can think of a way, please let me know.

**Comment by facuspagnuolo** [comment]
Yes, I'm sure. The `push` command will upload the source code of your smart contract to the blockchain, in this case, `Basil`'s source code. Then, you are using the `create` command to create a new upgradeable instance of that contract, which means you will be creating a new proxy pointing to the source code you uploaded in the first step. Then, the address of your upgradeable smart contract is actually the address of the proxy contract, in this case, the address stored in the `proxies.Basil.address` field of the `zos.<network>.json` file.

**Comment by roschler** [comment]
@facuspagnuolo Franco, I agree with what you are saying as to the relationship between the elements we are discussing.  I'm not contradicting you.  I _am_ questioning the Basil tutorial as to its instructions on what address should be exported to the BASIL_ADDRESS environment variable.  If the tutorial is right, then it is telling the reader to use the `app` address and not the BasilERC721 proxy address. 

Here's are the results of a tutorial execution I did right now, using the original tutorial, not my enhanced one, straight from this URL:

https://docs.zeppelinos.org/docs/basil.html

I wiped my original _basil_ directory and started from a completely new, blank directory.  Here is the state of my `zos.local.json` file right after the `zos push` of the upgraded _BasilERC721Token_, so you know that the address values I refer to hereon are exactly what you see in this text:

```sh
cat zos.local.json
```
```json
{
  "contracts": {
    "Basil": {
      "address": "0x5017a545b09ab9a30499de7f431df0855bcb7275",
      "bytecodeHash": "89682edf286eaccff951b5e4a0637b2e4dcab55c43f15476e305b5fb868bf533"
    }
  },
  "proxies": {
    "Basil": [
      {
        "address": "0x87148659ea177240c7b41f4e3e340cd7f9b63ce2",
        "version": "0.0.1",
        "implementation": "0xfc628dd79137395f3c9744e33b1c5de554d94882"
      }
    ]
  },
  "app": {
    "address": "0xb09bcc172050fbd4562da8b229cf3e45dc3045a6"
  },
  "version": "0.0.2",
  "package": {
    "address": "0xdb56f2e9369e0d7bd191099125a3f6c370f8ed15"
  },
  "provider": {
    "address": "0x4bf749ec68270027c5910220ceab30cc284c7ba2"
  }
```
Here is the screen output from the `zos push` command of the upgraded _BasilERC721Token_, right before you export the address to BASIL_ADDRESS:

![image](https://user-images.githubusercontent.com/4660487/41114836-9b8549fc-6a53-11e8-980d-7911fe323c54.png)

the lines in green are log output lines and the line in white is the push command output.  The tutorial says exactly this at this point:

```This will print the address of the deployed Basil contract. Let's export this value to use it later:

export BASIL_ADDRESS=<address>```

If you look at the address that is "printed" (in white), that address matches the `app` address in the `zos.local.json` file:

```0xb09bcc172050fbd4562da8b229cf3e45dc3045a6```

not the `proxies.Basil.address` address:

```0x87148659ea177240c7b41f4e3e340cd7f9b63ce2```

It seems to me that the tutorial is telling you to use the `app` address and unless I misunderstood you, you are saying that the `proxies.Basil.address` should go in the BASIL_ADDRESS environment variable?  If I'm right about this, then I feel the tutorial needs some rework at this step, especially since if you look at my screenshot again, **the `proxies.Basil.address` address isn't shown anywhere in the screen**.  I hope this helps.

**Comment by roschler** [comment]
I'm using this issue to keep a record of my explorations through the `zos-cli` code.  

While tracing I found the source code line that during a `zos push` command writes the singular line of output via the ZOS _StdOut_ library module.  I'm referring to the address referenced in the Basil tutorial that is to be assigned to the BASIL_ADDRESS environment variable, which should be the Basil proxy contract address.  

As you can see below it's definitely the _app_ address that is output and not the Basil proxy contract address:

```js
(0, _stdout2.default)(appController.isLib() ? appController.packageAddress : appController.appAddress);
```
I checked and _isLib()_ is FALSE at the time of execution.  Even if it weren't, the code still wouldn't output the proxy contract address but would output the package address instead.

**Comment by roschler** [comment]
@facuspagnuolo I found the problem with the Basil tutorial.  It's telling you to copy the address but at the wrong step.  Currently it tells you to take the address output during the `push` command and use that for the BASIL_ADDRESS environment variable.  As I said, the `push` command outputs the `app` address.

The Basil proxy contract address is output during the `zos create` command, when the Basil _proxy_ contract is created.  That step outputs the content below:

```sh
Creating Basil proxy and calling initialize(address) with "0xe49e6c32937fe9b9e73bc4885d090f9f6d8cd77f"...
 TX receipt received: 0xb59ce03767a7dfa7267d009de460795b5ddc01f1482f8031c3d8cc8b91f7c23b
 Basil proxy: 0x16163cc89d6d0aa54b846e30667baa1592ff0e40
Successfully written zos.local.json
```
I will finish up my revised version of the Basil tutorial, and that version will tell people to copy the address from the `zos create` command for the Basil contract, by copying the address shown next to the `Basil proxy` text label in the output above.  I'll do that once I figure out why I'm still getting a `revert()` exception due to the `onlyOwner` test failing on the `setToken()` call.  Working on that now.

**Comment by facuspagnuolo** [comment]
I consider the initial question answered, please consider opening new issues in the Basil repo if needed. Thanks @roschler
