### ISSUE TITLE
Change name of "create" command to "createproxy"?

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-cli#245]
Having spent the last 11 days working heavily with the ZOS library (fascinating thing you've built), there is one thing that was somewhat confusing to me while learning the ZOS commands via the Basil tutorial, and that is the `create` command.  Given all the uncertainty a new ZOS user has as to what command does what, having such a _generic_ name for this command made remembering what it does hard for me to remember.

Eventually I realized that is the specific command that creates the _proxy_ for the Basil contract.  Had the command been something like `createproxy` that bit of uncertainty would have not occurred.  My greater worry is that when the ZOS commands expand in the future (almost certainly), especially if there are new elements not related to proxying contracts, that command name will be even more confusing.

Not a big thing, but I wanted to mention it.

**Comment by facuspagnuolo** [comment]
We actually we did the other way around. We first called it `create-proxy` and then renamed it to simply `create`, see  #117. The idea was to abstract the user we are using proxies to create upgradeable contracts, which is the real intention of that command, to create a new upgradeable instance of a contract. Thanks for your contributions and interest in zOS!
