### ISSUE TITLE
How does multiple inheritance affect an upgrade command?

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-cli#246]
In the Basil tutorial, when you upgrade the Basil contract to the _BasilERC721_, you execute the following command:

```zos add BasilERC721:Basil```

How would this command change, if at all, if the BasilERC721 contract also inherited from one or more contracts other than the _Basil_ contract?  

Also, does multiple inheritance create any grief/problems for contracts proxied with ZOS?  I think some docs on this subject would be helpful if there aren't any yet.  Also, I personally would like to know what happens "behind the scenes" when you reference the base contract during an `add` command and how it affects what happens to the _zos.*.json_ file and how it changes what happens during a deploy.

At some point it wouldn't hurt to have the code that executes when you run a `zos add` command, scan the source of the newly added contract for inherited contracts; by inspecting the contract declaration line for inherited parent contracts and process them automatically without the user having to append them to `add` command.

**Comment by facuspagnuolo** [comment]
We are still exploring this idea, see https://github.com/zeppelinos/labs/issues/41

**Comment by facuspagnuolo** [comment]
Answering your question, inheriting one or many contracts will result in a single contract at the end. That's the bytecode that `zos` will be adding when doing `zos add X`. The only thing you should consider is to handle carefully an upgrade in case you need to change many contracts of the hierarchy. For example, if you need to add a new state variable to the base contract, you will be defining a new storage layout, which means that your previous proxy storage layout will be probably no longer compatible.

As I said, we are still exploring this topic. Closing this issue in favour of zeppelinos/labs#41

**Comment by roschler** [comment]
Thanks.
