### ISSUE TITLE
Add command to automate verification on an Ethereum explorer

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-cli#274]
Add a new command (`verify`?) to use a blockchain explorer API to automatically verify a deployed set of contracts.

**Comment by frangio** [comment]
Does this refer to the logic contracts or the proxies?

Last time I checked Etherscan did not have an API for this, and the verification form has a captcha.

**Comment by spalladino** [comment]
Currently @jcarpanelli is working on this
