### ISSUE TITLE
TypeError: Cannot create property 'stdlib' on string 'zos.json(@1.1.0)

### ISSUE THREAD

**Issue by roson9527** [zeppelinos/zos-cli#333]
node: 10.6.0
truffle: 4.1.13

zos.json
```
{
  "name": "gar",
  "version": "0.1.0",
  "contracts": {
    "RBACWithAdmin": "RBACWithAdmin",
  },
  "stdlib": {
    "name": "openzeppelin-zos",
    "version": "1.9.1"
  }
}
```
package.json
```
"dependencies": {
    "chai": "^4.1.2",
    "openzeppelin-zos": "^1.9.1",
    "zos": "^1.1.0"
  },
```

test.js
```
contract('test', async (accounts) => {
    let owner = accounts[1];
    beforeEach(async () => {
        this.app = await TestApp('zos.json', {
            from: owner
        });
    });

    it('testA', async () => {
    });
});
```
cmd
```
NODE_ENV=test truffle test
```
when zos version is 1.0.0 it's working :(

**Comment by spalladino** [comment]
@roson9527 seems the docs are wrong w.r.t. TestApp usage. Can you try removing the first parameter (ie `zos.json`) from the call to TestApp? I'll work on a fix (on either docs or API, or both) in the meantime. Thanks!

**Comment by joecoope** [comment]
Hey gentlemen, I was researching your project a few weeks ago and and somehow triggered email updates on your work. I have tried muting the thread but they continue.. Can you help? Its clogging my inbox and tbh I don't code so I don't really understand what your talking about. Lol
Regards
Joe
Sent from my Boost Zume 5 on the Telstra Mobile Network
On 24 Jul 2018 5:05 AM, Santiago Palladino <notifications@github.com> wrote:


@roson9527<https://github.com/roson9527> seems the docs are wrong w.r.t. TestApp usage. Can you try removing the first parameter (ie zos.json) from the call to TestApp? I'll work on a fix (on either docs or API, or both) in the meantime. Thanks!

**Comment by spalladino** [comment]
@joecoope make sure you are not watching or following the repository or organization, even if you have muted individual threads. If the issue persists, please [contact Github directly](https://github.com/contact), as there is nothing we can do from our end.

**Comment by kabriel** [comment]
getting this issue when i updated to 1.1 as well

**Comment by spalladino** [comment]
@kabriel please invoke `TestApp` as `TestApp(null, { from: yourAccount })`. The first parameter will be dropped in the next release with #335.

**Comment by joecoope** [comment]
OK, thanks.
Sent from my Boost Zume 5 on the Telstra Mobile Network
On 24 Jul 2018 11:34 PM, Santiago Palladino <notifications@github.com> wrote:


@joecoope<https://github.com/joecoope> make sure you are not watching or following the repository or organization, even if you have muted individual threads. If the issue persists, please contact Github directly<https://github.com/contact>, as there is nothing we can do from our end.
