### ISSUE TITLE
Deploying to mainnet error: nonce too low

### ISSUE THREAD

**Issue by wagner-daniel** [zeppelinos/zos-cli#334]
I tried to deploy my application to mainnet, but I get an error that my nonce is too low.

I deployed it successfully to my local net and to ropsten with those commands.

zos push --network ropsten
zos create Token --init initialize --args 1234 --network ropsten

but when I run it on mainnet:

zos push --network mainnet

Compilation was successful. Then I got this

Writing artifacts to ./build/contracts

Deploying new UpgradeabilityProxyFactory...
Deployed UpgradeabilityProxyFactory (address)
Deploying new Package...
Successfully written zos.mainnet.json
nonce too low

The UpgradeabilityProxyFactory was deployed to mainnet, but then the nonce is always to low

I use zos version 1.1,0 and zos-lib version 1.3.0

**Comment by spalladino** [comment]
Hey @wagner-daniel, thanks for the report! Quick question: were you using the mainnet account for issuing any other transactions at the same time from a console, or somewhere else? It could have been possible that the nonce got out of sync if you were sending transactions from two different apps (the zOS CLI, and another one) at the same time. Was this the case? If not, did the issue manifest itself again, or was a one-time error?

**Comment by gus-canya** [comment]
Hey @wagner-daniel 
May I take a look to your truffle-config.js mainnet configuration? 

I'm trying to push to mainnet with no success.

**Comment by gus-canya** [comment]
As an addition to this issue. 

Im trying to deploy a set of contracts. 
These are the steps I've followed (the same steps work fine in infura v3 ropsten): 

```
zos add
```

Result: 

```
{
  "name": "0.1.0",
  "version": "0.1.3",
  "contracts": {
    "MyContract": "MyContract"
  }
}
```

```
zos push --network mainnet_infura
```

truffle-config.js

```
const HDWalletProvider = require("truffle-hdwallet-provider");

const Web3 = require("web3");
const web3 = new Web3();
const gasPrice = web3.utils.toWei('7.5', 'gwei');

module.exports = {
  networks: {
    mainnet_infura: {
      network_id: 1,
      // gas: 7996144, // not needed, set by default
      gasPrice: gasPrice,
      provider: function () {
        return new HDWalletProvider(process.env.WALLET_MNEMONIC, `https://mainnet.infura.io/v3/${process.env.INFURA_API_KEY}`)
      }
    },
```

Results in: 

```
Compiling contracts...
//... 
Writing artifacts to ./build/contracts

Deploying new UpgradeabilityProxyFactory...
Deployed UpgradeabilityProxyFactory 0x60abacaab5b33ba081749553d810944e3eb85dc4
Deploying new Package...
Deployed Package 0xb304cdf3ad373c47255b3042fd1a918b30d9984f
Deploying new AppDirectory...
Deployed AppDirectory 0x4d17e7b4390622c63b5a7722c5aad80948078983
Adding new version...
Successfully written zos.mainnet_infura.json
nonce too low
```

What's been written in zos.mainnet_infura.json: 

```
{
  "contracts": {},
  "proxies": {}
} 
```

----

Ideas: 

- Is there a way to delay the time between each transaction so the nonce gets synced?
- I noticed that there are additional txs in etherscan associated to my address that are not _Contract creation_s. What are these? Can I do them manually? 
- Where is the code of the contracts being created behind the scenes? `UpgradeabilityProxyFactory...`, `Package...`, `AppDirectory...`

I've tried these solutions with no success: 
https://ethereum.stackexchange.com/a/50038/31101

**Comment by spalladino** [comment]
Thanks a lot for the info @gus-canya! Quick question: what version of the CLI are you working with?

As for your questions:
> Is there a way to delay the time between each transaction so the nonce gets synced?
> I noticed that there are additional txs in etherscan associated to my address that are not Contract creations . What are these? Can I do them manually?
> Where is the code of the contracts being created behind the scenes? UpgradeabilityProxyFactory..., Package..., AppDirectory...

1- Not atm, but it could be a viable workaround if we cannot find a more robust solution.
2- Some of these contracts are "registered" as part of others, not necessarily in the constructor, so that needs to be done on separate txs.
3- You can find that on [zos-lib](https://github.com/zeppelinos/zos-lib/tree/master/contracts)

As another test, can you try either:
- Using non-infura infrastructure, preferrably a **single** node you control?
- Using the [nonce-subprovider](https://github.com/MetaMask/provider-engine) to keep track of your nonces client-side?

**Comment by gus-canya** [comment]
@spalladino `zos --version => 1.1.0`

**Comment by wagner-daniel** [comment]
@spalladino I did not had any other transactions while I tried deploying. The issue occured a second time, then I looked at the source and did every transaction manually and created the zos file by hand (for the hashes of the contract I wrote a small node script to calculate them based on your cli code). After I did this the second command worked as expected:

`zos create Token --init initialize --args 1234 --network mainnet`

It called the initializer of the Token contract and the contract is live now :)
It also updated the zos file, so the issue was only while deploying the OS.

**Comment by gus-canya** [comment]
Hey @wagner-daniel 
I ended up setting my own parity node as @spalladino suggested. It was quite easy and the deployment went through without errors. 

You'll just need to wait for the node to sync and then execute the zos commands with your node URL as in ropsten.

**Comment by spalladino** [comment]
@wagner-daniel could you confirm if you were working with Infura?

**Comment by wagner-daniel** [comment]
@spalladino Yes I used Infura

**Comment by jbcarpanelli** [comment]
Let's close this issue for now. We implemented a hotfix [here](https://github.com/zeppelinos/zos/pull/63).
Also, this issue is from `truffle-hdwallet-provider` and is being discussed [here](https://github.com/trufflesuite/truffle-hdwallet-provider/issues/65).
