### ISSUE TITLE
CLI outputs `successfully written` message before the error message when failing

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-cli#337]
Sample output from the CLI, taken from #334:
```
Deploying new UpgradeabilityProxyFactory...
Deployed UpgradeabilityProxyFactory (address)
Deploying new Package...
Successfully written zos.mainnet.json
nonce too low
```

It's odd that the sequence of messages jumps from the actions being performed, to a "successfully written message", to an error message that corresponds to a previous action.

Move the error message right next to the action that caused it, and consider rephrasing "successfully written message" for something that does not start with successful. We can also remove the "successfully written"  altogether, and replace it with a "successfully completed" only shown when there were no errors.

**Comment by jbcarpanelli** [comment]
I think the best thing to do here is just switch the order between the error and the `successfully written zos.network.json`, and also change the latter to a not so friendly and positive message to avoid confusion.

**Comment by spalladino** [comment]
Agree. We could even drop the `successfully written` message, I'm not sure it delivers much useful information.
