### ISSUE TITLE
Document package.zos.json files structure

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-cli#36]
Add documentation (not in the README) on the structure of package.zos.json and package.zos.network.json files, and how they are affected by each command. Consider adding them in a separate md file or wiki, and then move it to the central doc site.

**Comment by fiiiu** [comment]
Put this in Markdown format in `zos-docs/docs/docs/package.md`. 

There is a placeholder file already there, please keep the current header:
```
---
id: package
title: Package files format
sidebar_label: Package files format
---
```
and add content below *without* a top level (#) title.

**Comment by fiiiu** [comment]
Closed in https://github.com/zeppelinos/zos-docs/pull/34.
