### ISSUE TITLE
Compile contracts before sync

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-cli#39]
The `sync` subcommand deploys contracts to the network. It should compile them beforehand if necessary.

**Comment by spalladino** [comment]
Note that this must assume that the user is using a certain tool for compiling (such as truffle), which may tie us too much to that specific tool.

**Comment by martriay** [comment]
@spalladino I think that making this assumption for the time being it's an acceptable tradeoff in favor of the DX.

**Comment by spalladino** [comment]
Ok, let's move forward then!

**Comment by martriay** [comment]
Addressed in https://github.com/zeppelinos/zos-cli/pull/108.
