### ISSUE TITLE
Using deploy-all injects a stdlib but sync can't find it's address 

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos-cli#50]
When using deploy-all, a stdlib's contracts are deployed in a directory and this directory's address is written into the package.zos.network.json file.

However, if he sync command is ran afterwards, the stdlib's deployed address is sought for within the node_modules package, ignoring the injected version.

As a result, using deploy-all is not really usable as is.

**Comment by ajsantander** [comment]
PR https://github.com/zeppelinos/zos-cli/pull/49

**Comment by spalladino** [comment]
Fixed via #58
