### ISSUE TITLE
CLI is unable to find deployed stdlib address in ropsten

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos-cli#51]
When sync is called with a stdlib set in package.zos.json, sync.js' handleStdlib is undefined, and so this line is called:
https://github.com/zeppelinos/zos-cli/blob/master/src/scripts/sync.js#L41

Which results in the AppDirectory contract's setStdlib being called with the name of the stdlib instead of the address. Note that AppDIrectory does not validate the received address, so the error is silent.

However when creating a stdlib entry proxy, as soon as the directory falls back to the stdlib provider, a revert is triggered.

**Comment by spalladino** [comment]
Fixed via #58
