### ISSUE TITLE
Consider extracting stdlib provider from on-chain package

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-cli#8]
Stdlib extracts the current contract provider from the `provider` address entry of the package per-network file. Consider extracting the provider address from the `package` on-chain (which should be immutable), instead of from a json file that could become out-of-sync.

**Comment by facuspagnuolo** [comment]
We already fixed this

**Comment by facuspagnuolo** [comment]
Wrong issue

**Comment by facuspagnuolo** [comment]
Closing in favor of #142 and #31
