### ISSUE TITLE
The README explains the [ALIAS] argument, but doesn't use it

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos-cli#87]
On the README there is a section that says:

>zos add-implementation [CONTRACT_NAME_N] --network [NETWORK]
>
>Where [CONTRACT_NAME] is the name of your Solidity contract, and [ALIAS] is the name under which it >will be registered in zeppelin_os.

I'm not sure if we should remove the explanation of ALIAS, or add it to the command call.

**Comment by facuspagnuolo** [comment]
Based on the new documentation site and READMEs, I think this is no longer true. At least, I cannot find a place mentioning what you're quoting, closing then!
